name: Integração contínua

on: [push]

env:
  # replace "github_username" with your GitHub username
  # replace "github.com/username/repo.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  MY_REPO: https://github.com/henrique-kenji/front.git
  # replace "long-lived_branch_name" with your branch name
  MY_BRANCH: main

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/username/master_repo.git

  # replace "master" with your master branch name
  MASTER_BRANCH: master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Instalação de dependências
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Merge para realização dos testes unitários
        run: |
          git clone https://github.com/henrique-kenji/servicos.git
          
      
      - name: Testes unitários com unittest
        run: 
            python -m testes.test
              
          
    
